import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';

await mkdir('api', { recursive: true });

await build({
  entryPoints: ['src/vercel-entry.ts'],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  outfile: 'api/index.js',
  packages: 'external',
  banner: {
    // Avoid "exports is not defined" / CJS interop issues at the edge of the bundle
    js: '// @generated by build-vercel.mjs — do not edit',
  },
  logLevel: 'info',
});

console.log('Bundled Vercel function → api/index.js');
