// @generated by build-vercel.mjs — do not edit

// src/vercel-entry.ts
import { handle } from "@hono/node-server/vercel";

// src/app.ts
import { Hono as Hono2 } from "hono";
import { cors } from "hono/cors";

// src/routes/routes.ts
import { Hono } from "hono";

// src/utils/response.ts
var success = (c, data, statusCode = 200) => {
  return c.json({ success: true, data }, statusCode);
};
var fail = (c, message = "internal server error", statusCode = 500, details = null) => {
  return c.json({ success: false, message, details }, statusCode);
};

// src/utils/errors.ts
var AppError = class extends Error {
  statusCode;
  details;
  constructor(message, statusCode = 500, details = null) {
    super(message);
    this.statusCode = statusCode;
    this.details = details;
  }
};
var NotFoundError = class extends AppError {
  constructor(message = "resource not found", details = null) {
    super(message, 404, details);
  }
};
var validationError = class extends AppError {
  constructor(message = "validaion failed", details = null) {
    super(message, 400, details);
  }
};

// src/utils/handler.ts
var handler = (fn) => {
  return async (c, next) => {
    try {
      const result = await fn(c, next);
      return success(c, result, 200);
    } catch (error) {
      if (error instanceof AppError) {
        return fail(c, error.message, error.statusCode, error.details);
      }
      if (error instanceof Error) {
        console.error(error.message);
        return fail(c, error.message, 500);
      }
      return fail(c, "Internal server error", 500);
    }
  };
};
var handler_default = handler;

// src/config/config.ts
var config = {
  baseurl: process.env.BASE_URL || process.env.HIANIME_BASE_URL || "https://hianime.lu",
  baseurl2: process.env.BASE_URL_2 || process.env.BASE_URL || process.env.HIANIME_BASE_URL || "https://hianime.lu",
  origin: process.env.CORS_ORIGIN || "*",
  port: Number(process.env.PORT) || 5e3,
  headers: {
    "User-Agent": process.env.SCRAPE_USER_AGENT || "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0"
  },
  logLevel: "INFO",
  enableLogging: process.env.ENABLE_LOGGING === "true",
  isProduction: process.env.NODE_ENV === "production",
  isDevelopment: process.env.NODE_ENV !== "production",
  isVercel: Boolean(process.env.VERCEL)
};
var config_default = config;

// src/services/axiosInstance.ts
var MAX_RETRIES = 3;
var RETRY_DELAY = 1e3;
var TIMEOUT = 1e4;
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
var axiosInstance = async (endpoint, options = {}) => {
  const { headers: customHeaders = {}, retries = MAX_RETRIES } = options;
  const url = config_default.baseurl + endpoint;
  let lastError = null;
  for (let attempt = 0; attempt < retries; attempt++) {
    try {
      if (attempt > 0) {
        const delay = RETRY_DELAY * Math.pow(2, attempt - 1);
        console.log(`Retry attempt ${attempt + 1}/${retries} after ${delay}ms delay...`);
        await sleep(delay);
      }
      console.log(`Fetching (attempt ${attempt + 1}/${retries}): ${url}`);
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), TIMEOUT);
      const response = await fetch(url, {
        headers: {
          ...config_default.headers || {},
          ...customHeaders,
          Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
          "Accept-Language": "en-US,en;q=0.5",
          "Accept-Encoding": "gzip, deflate, br",
          Connection: "keep-alive",
          "Upgrade-Insecure-Requests": "1",
          "Cache-Control": "max-age=0"
        },
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      console.log(`Response status: ${response.status}`);
      if (response.status === 429) {
        const retryAfter = response.headers.get("retry-after");
        const waitTime = retryAfter ? parseInt(retryAfter) * 1e3 : RETRY_DELAY * 2;
        console.warn(`Rate limited. Waiting ${waitTime}ms before retry...`);
        await sleep(waitTime);
        continue;
      }
      if (response.status >= 500 && response.status < 600) {
        throw new Error(`Server error: HTTP ${response.status}`);
      }
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }
      const data = await response.text();
      if (!data || data.length === 0) {
        throw new Error("Empty response received");
      }
      console.log(`Success: Received data length: ${data.length}`);
      return {
        success: true,
        data
      };
    } catch (error) {
      if (error instanceof Error) {
        lastError = error;
        console.error(
          `Fetch error (attempt ${attempt + 1}/${retries}) for ${endpoint}:`,
          error.message
        );
        if (error.name === "AbortError") {
          lastError = new Error("Request timeout - the external API took too long to respond");
        }
        if (error.message.includes("HTTP 40") && !error.message.includes("429")) {
          break;
        }
      }
      if (attempt === retries - 1) {
        break;
      }
    }
  }
  return {
    success: false,
    message: lastError?.message || "Unknown error occurred"
  };
};

// src/extractor/extractHomepage.ts
import { load } from "cheerio";
var extractHomepage = (html) => {
  const $ = load(html);
  const response = {
    spotlight: [],
    trending: [],
    topAiring: [],
    mostPopular: [],
    mostFavorite: [],
    latestCompleted: [],
    latestEpisode: [],
    newAdded: [],
    topUpcoming: [],
    top10: {
      today: null,
      week: null,
      month: null
    },
    genres: []
  };
  const $spotlight = $(".deslide-wrap .swiper-wrapper .swiper-slide");
  const $trending = $("#trending-home .swiper-container .swiper-slide");
  const $featured = $("#anime-featured .anif-blocks .row .anif-block");
  const $home = $(".block_area.block_area_home");
  const $top10 = $(".block_area .cbox");
  const $genres = $(".sb-genre-list");
  $($spotlight).each((i, el) => {
    const obj = {
      title: null,
      alternativeTitle: null,
      id: null,
      poster: null,
      rank: i + 1,
      type: null,
      quality: null,
      duration: null,
      aired: null,
      synopsis: null,
      episodes: {
        sub: null,
        dub: null,
        eps: null
      }
    };
    obj.id = $(el).find(".desi-buttons a").first().attr("href")?.split("/").at(-1) || null;
    obj.poster = $(el).find(".deslide-cover .film-poster-img").attr("data-src") || null;
    const titles = $(el).find(".desi-head-title");
    obj.title = titles.text();
    obj.alternativeTitle = titles.attr("data-jname") || null;
    obj.synopsis = $(el).find(".desi-description").text().trim();
    const details = $(el).find(".sc-detail");
    obj.type = details.find(".scd-item").eq(0).text().trim();
    obj.duration = details.find(".scd-item").eq(1).text().trim();
    obj.aired = details.find(".scd-item.m-hide").text().trim();
    obj.quality = details.find(".scd-item .quality").text().trim();
    obj.episodes.sub = Number(details.find(".tick-sub").text().trim()) || null;
    obj.episodes.dub = Number(details.find(".tick-dub").text().trim()) || null;
    const epsText = details.find(".tick-eps").length ? details.find(".tick-eps").text().trim() : details.find(".tick-sub").text().trim();
    obj.episodes.eps = Number(epsText) || null;
    response.spotlight.push(obj);
  });
  $($trending).each((i, el) => {
    const obj = {
      title: null,
      alternativeTitle: null,
      rank: i + 1,
      poster: null,
      id: null
    };
    const titleEl = $(el).find(".item .film-title");
    obj.title = titleEl.text();
    obj.alternativeTitle = titleEl.attr("data-jname") || null;
    const imageEl = $(el).find(".film-poster");
    obj.poster = imageEl.find("img").attr("data-src") || null;
    obj.id = imageEl.attr("href")?.split("/").at(-1) || null;
    response.trending.push(obj);
  });
  $($featured).each((i, el) => {
    const data = $(el).find(".anif-block-ul ul li").map((index, item) => {
      const obj = {
        title: null,
        alternativeTitle: null,
        id: null,
        poster: null,
        type: null,
        duration: null,
        episodes: {
          sub: null,
          dub: null,
          eps: null
        }
      };
      const titleEl = $(item).find(".film-detail .film-name a");
      obj.title = titleEl.attr("title") || null;
      obj.alternativeTitle = titleEl.attr("data-jname") || null;
      obj.id = titleEl.attr("href")?.split("/").at(-1) || null;
      obj.poster = $(item).find(".film-poster .film-poster-img").attr("data-src") || null;
      const infoItems = $(item).find(".fd-infor .fdi-item");
      obj.type = infoItems.eq(0).text().trim() || null;
      obj.duration = infoItems.eq(1).text().trim() || null;
      obj.episodes.sub = Number($(item).find(".tick .tick-sub").text()) || null;
      obj.episodes.dub = Number($(item).find(".tick .tick-dub").text()) || null;
      const epsText = $(item).find(".fd-infor .tick-eps").length ? $(item).find(".fd-infor .tick-eps").text() : $(item).find(".fd-infor .tick-sub").text();
      obj.episodes.eps = Number(epsText) || null;
      return obj;
    }).get();
    const dataType = $(el).find(".anif-block-header").text().replace(/\s+/g, "");
    const normalizedDataType = dataType.charAt(0).toLowerCase() + dataType.slice(1);
    response[normalizedDataType] = data;
  });
  $($home).each((i, el) => {
    const data = $(el).find(".tab-content .film_list-wrap .flw-item").map((index, item) => {
      const obj = {
        title: null,
        alternativeTitle: null,
        id: null,
        poster: null,
        type: null,
        // Default
        episodes: {
          sub: null,
          dub: null,
          eps: null
        }
      };
      const titleEl = $(item).find(".film-detail .film-name .dynamic-name");
      obj.title = titleEl.attr("title") || null;
      obj.alternativeTitle = titleEl.attr("data-jname") || null;
      obj.id = titleEl.attr("href")?.split("/").at(-1) || null;
      obj.poster = $(item).find(".film-poster img").attr("data-src") || null;
      const episodesEl = $(item).find(".film-poster .tick");
      obj.episodes.sub = Number($(episodesEl).find(".tick-sub").text()) || null;
      obj.episodes.dub = Number($(episodesEl).find(".tick-dub").text()) || null;
      const epsText = $(episodesEl).find(".tick-eps").length ? $(episodesEl).find(".tick-eps").text() : $(episodesEl).find(".tick-sub").text();
      obj.episodes.eps = Number(epsText) || null;
      return obj;
    }).get();
    const dataType = $(el).find(".cat-heading").text().replace(/\s+/g, "");
    const normalizedDataType = dataType.charAt(0).toLowerCase() + dataType.slice(1);
    if (normalizedDataType === "newOnHiAnime") {
      response.newAdded = data;
    } else if (normalizedDataType in response) {
      response[normalizedDataType] = data;
    }
  });
  const extractTopTen = (id) => {
    const res = $top10.find(`${id} ul li`).map((i, el) => {
      const obj = {
        title: $(el).find(".film-name a").text() || null,
        rank: i + 1,
        alternativeTitle: $(el).find(".film-name a").attr("data-jname") || null,
        id: $(el).find(".film-name a").attr("href")?.split("/").pop() || null,
        poster: $(el).find(".film-poster img").attr("data-src") || null
      };
      return obj;
    }).get();
    return res;
  };
  response.top10.today = extractTopTen("#top-viewed-day");
  response.top10.week = extractTopTen("#top-viewed-week");
  response.top10.month = extractTopTen("#top-viewed-month");
  $($genres).find("li").each((i, el) => {
    const genre = $(el).find("a").attr("title")?.toLocaleLowerCase() || "";
    response.genres.push(genre);
  });
  return response;
};

// src/controllers/homepage.controller.ts
var homepageController = async () => {
  console.log("Fetching homepage data from external API...");
  const result = await axiosInstance("/home");
  if (!result.success || !result.data) {
    console.error("Homepage fetch failed:", result.message);
    throw new validationError(result.message || "Failed to fetch homepage");
  }
  return extractHomepage(result.data);
};
var homepage_controller_default = homepageController;

// src/extractor/extractDetailpage.ts
import { load as load2 } from "cheerio";
var extractDetailpage = (html) => {
  const $ = load2(html);
  const obj = {
    title: null,
    alternativeTitle: null,
    japanese: null,
    id: null,
    poster: null,
    rating: null,
    type: null,
    is18Plus: false,
    episodes: {
      sub: null,
      dub: null,
      eps: null
    },
    synopsis: null,
    synonyms: null,
    aired: {
      from: null,
      to: null
    },
    premiered: null,
    duration: null,
    status: null,
    MAL_score: null,
    genres: [],
    studios: [],
    producers: [],
    moreSeasons: [],
    related: [],
    mostPopular: [],
    recommended: []
  };
  const main = $("#ani_detail .anis-content");
  const moreSeasons = $("#main-content .block_area-seasons");
  const relatedAndMostPopular = $("#main-sidebar .block_area");
  const recommended = $(
    ".block_area.block_area_category .tab-content .block_area-content .film_list-wrap .flw-item"
  );
  obj.poster = main.find(".film-poster .film-poster-img").attr("src") || null;
  obj.is18Plus = Boolean(main.find(".film-poster .tick-rate").length > 0);
  const titleEl = main.find(".anisc-detail .film-name");
  obj.title = titleEl.text();
  obj.alternativeTitle = titleEl.attr("data-jname") || null;
  const info = main.find(".film-stats .tick");
  obj.rating = info.find(".tick-pg").text();
  obj.episodes.sub = Number(info.find(".tick-sub").text()) || null;
  obj.episodes.dub = Number(info.find(".tick-dub").text()) || null;
  obj.episodes.eps = info.find(".tick-eps").length ? Number(info.find(".tick-eps").text()) || null : Number(info.find(".tick-sub").text()) || null;
  obj.type = info.find(".item").first().text();
  const idLink = main.find(".film-buttons .btn");
  obj.id = idLink.length ? idLink.attr("href")?.split("/").at(-1) || null : null;
  const moreInfo = main.find(".anisc-info-wrap .anisc-info .item");
  moreInfo.each((i, el) => {
    const name = $(el).find(".item-head").text();
    switch (name) {
      case "Overview:":
        obj.synopsis = $(el).find(".text").text().trim();
        break;
      case "Japanese:":
        obj.japanese = $(el).find(".name").text();
        break;
      case "Synonyms:":
        obj.synonyms = $(el).find(".name").text();
        break;
      case "Aired:": {
        let aired = $(el).find(".name").text().split("to");
        obj.aired.from = aired[0].trim();
        if (aired.length > 1) {
          const secondPart = aired[1].trim();
          obj.aired.to = secondPart === "?" ? null : secondPart;
        } else {
          obj.aired.to = null;
        }
        break;
      }
      case "Premiered:":
        obj.premiered = $(el).find(".name").text();
        break;
      case "Duration:":
        obj.duration = $(el).find(".name").text();
        break;
      case "Status:":
        obj.status = $(el).find(".name").text();
        break;
      case "MAL Score:":
        obj.MAL_score = $(el).find(".name").text();
        break;
      case "Genres:":
        obj.genres = $(el).find("a").map((i2, genre) => $(genre).text()).get();
        break;
      case "Studios:":
        obj.studios = $(el).find("a").map((i2, studio) => $(studio).attr("href")?.split("/").at(-1)).get();
        break;
      case "Producers:":
        obj.producers = $(el).find("a").map((i2, producer) => $(producer).attr("href")?.split("/").at(-1)).get();
        break;
      default:
        break;
    }
  });
  if (moreSeasons.length) {
    $(moreSeasons).find(".os-list .os-item").each((i, el) => {
      const innerObj = {
        title: null,
        alternativeTitle: null,
        id: null,
        poster: null,
        isActive: false
      };
      innerObj.title = $(el).attr("title") || null;
      innerObj.id = $(el).attr("href")?.split("/").pop() || null;
      innerObj.alternativeTitle = $(el).find(".title").text();
      const posterStyle = $(el).find(".season-poster").attr("style");
      if (posterStyle) {
        const match = posterStyle.match(/url\((['"])?(.*?)\1\)/);
        innerObj.poster = match ? match[2] : null;
      }
      innerObj.isActive = $(el).hasClass("active");
      obj.moreSeasons.push(innerObj);
    });
  }
  const extractRelatedAndMostPopular = (index, array) => {
    relatedAndMostPopular.eq(index).find(".cbox .ulclear li").each((i, el) => {
      const innerObj = {
        title: null,
        alternativeTitle: null,
        id: null,
        poster: null,
        type: null,
        episodes: {
          sub: null,
          dub: null,
          eps: null
        }
      };
      const titleEl2 = $(el).find(".film-name .dynamic-name");
      innerObj.title = titleEl2.text();
      innerObj.alternativeTitle = titleEl2.attr("data-jname") || null;
      innerObj.id = titleEl2.attr("href")?.split("/").pop() || null;
      const infor = $(el).find(".fd-infor .tick");
      innerObj.type = infor.contents().filter((i2, el2) => {
        return el2.type === "text" && $(el2).text().trim() !== "";
      }).text().trim();
      innerObj.episodes.sub = Number(infor.find(".tick-sub").text()) || null;
      innerObj.episodes.dub = Number(infor.find(".tick-dub").text()) || null;
      const epsEl = infor.find(".tick-eps").length ? infor.find(".tick-eps").text() : infor.find(".tick-sub").text();
      innerObj.episodes.eps = Number(epsEl) || null;
      innerObj.poster = $(el).find(".film-poster .film-poster-img").attr("data-src") || null;
      array.push(innerObj);
    });
  };
  if (relatedAndMostPopular.length > 1) {
    extractRelatedAndMostPopular(0, obj.related);
    extractRelatedAndMostPopular(1, obj.mostPopular);
  } else {
    extractRelatedAndMostPopular(0, obj.mostPopular);
  }
  recommended.each((i, el) => {
    const innerObj = {
      title: null,
      alternativeTitle: null,
      id: null,
      poster: null,
      type: null,
      duration: null,
      episodes: {
        sub: null,
        dub: null,
        eps: null
      },
      is18Plus: false
    };
    const titleEl2 = $(el).find(".film-detail .film-name .dynamic-name");
    innerObj.title = titleEl2.text();
    innerObj.alternativeTitle = titleEl2.attr("data-jname") || null;
    innerObj.id = titleEl2.attr("href")?.split("/").pop() || null;
    innerObj.type = $(el).find(".fd-infor .fdi-item").first().text();
    innerObj.duration = $(el).find(".fd-infor .fdi-duration").text();
    innerObj.poster = $(el).find(".film-poster .film-poster-img").attr("data-src") || null;
    innerObj.is18Plus = $(el).find(".film-poster").has(".tick-rate").length > 0;
    innerObj.episodes.sub = Number($(el).find(".film-poster .tick .tick-sub").text()) || null;
    innerObj.episodes.dub = Number($(el).find(".film-poster .tick .tick-dub").text()) || null;
    const epsText = $(el).find(".film-poster .tick .tick-eps").length ? $(el).find(".film-poster .tick .tick-eps").text() : $(el).find(".film-poster .tick .tick-sub").text();
    innerObj.episodes.eps = Number(epsText) || null;
    obj.recommended.push(innerObj);
  });
  return obj;
};

// src/controllers/detailpage.controller.ts
var detailpageController = async (c) => {
  const id = c.req.param("id");
  const result = await axiosInstance(`/${id}`);
  if (!result.success || !result.data) {
    throw new validationError(
      result.message || "Failed to fetch detail page",
      "maybe id is incorrect : " + id
    );
  }
  return extractDetailpage(result.data);
};
var detailpage_controller_default = detailpageController;

// src/extractor/extractListpage.ts
import { load as load3 } from "cheerio";
var extractListPage = (html) => {
  const $ = load3(html);
  const response = [];
  const items = $(".flw-item");
  if (items.length < 1) {
    return {
      pageInfo: {
        currentPage: 1,
        hasNextPage: false,
        totalPages: 1
      },
      response: [],
      top10: {
        today: [],
        week: [],
        month: []
      },
      genres: []
    };
  }
  $(".block_area-content.block_area-list.film_list .film_list-wrap .flw-item").each(
    (i, el) => {
      const obj = {
        title: null,
        alternativeTitle: null,
        id: null,
        poster: null,
        episodes: {
          sub: null,
          dub: null,
          eps: null
        },
        type: null,
        duration: null
      };
      obj.poster = $(el).find(".film-poster .film-poster-img").attr("data-src") || null;
      obj.episodes.sub = Number($(el).find(".film-poster .tick .tick-sub").text()) || null;
      obj.episodes.dub = Number($(el).find(".film-poster .tick .tick-dub").text()) || null;
      const epsText = $(el).find(".film-poster .tick .tick-eps").length ? $(el).find(".film-poster .tick .tick-eps").text() : $(el).find(".film-poster .tick .tick-sub").text();
      obj.episodes.eps = Number(epsText) || null;
      const titleEl = $(el).find(".film-detail .film-name .dynamic-name");
      obj.title = titleEl.text();
      obj.alternativeTitle = titleEl.attr("data-jname") || null;
      const href = titleEl.attr("href") || "";
      const id = href.split("/").at(-1) || "";
      obj.id = id.includes("?ref=") ? id.split("?")[0] : id;
      obj.type = $(el).find(".fd-infor .fdi-item").first().text();
      obj.duration = $(el).find(".fd-infor .fdi-duration").text();
      response.push(obj);
    }
  );
  const paginationEl = $(".pre-pagination .pagination .page-item");
  let currentPage, hasNextPage, totalPages;
  if (!paginationEl.length) {
    currentPage = 1;
    hasNextPage = false;
    totalPages = 1;
  } else {
    currentPage = Number(paginationEl.find(".active .page-link").text());
    hasNextPage = !paginationEl.last().hasClass("active");
    totalPages = hasNextPage ? Number(paginationEl.last().find(".page-link").attr("href")?.split("page=").at(-1)) || 1 : Number(paginationEl.last().find(".page-link").text()) || 1;
  }
  const pageInfo = {
    totalPages,
    currentPage,
    hasNextPage
  };
  const $top10 = $(".block_area .cbox");
  const $genres = $(".sb-genre-list");
  const extractTopTen = (id) => {
    const res = $top10.find(`${id} ul li`).map((i, el) => {
      const obj = {
        title: $(el).find(".film-name a").text() || null,
        rank: i + 1,
        alternativeTitle: $(el).find(".film-name a").attr("data-jname") || null,
        id: $(el).find(".film-name a").attr("href")?.split("/").pop() || null,
        poster: $(el).find(".film-poster img").attr("data-src") || null
      };
      return obj;
    }).get();
    return res;
  };
  const top10 = {
    today: extractTopTen("#top-viewed-day"),
    week: extractTopTen("#top-viewed-week"),
    month: extractTopTen("#top-viewed-month")
  };
  const genres = [];
  $($genres).find("li").each((i, el) => {
    const genre = $(el).find("a").attr("title")?.toLocaleLowerCase() || "";
    if (genre) genres.push(genre);
  });
  return { pageInfo, response, top10, genres };
};

// src/controllers/listpage.controller.ts
var listpageController = async (c) => {
  const validateQueries = [
    "top-airing",
    "most-popular",
    "most-favorite",
    "completed",
    "recently-added",
    "recently-updated",
    "top-upcoming",
    "genre",
    "producer",
    "az-list",
    "subbed-anime",
    "dubbed-anime",
    "movie",
    "tv",
    "ova",
    "ona",
    "special",
    "events"
  ];
  const query = c.req.param("query")?.toLowerCase() || "";
  if (!validateQueries.includes(query))
    throw new validationError("invalid query", { validateQueries });
  let category = c.req.param("category") || null;
  const page = c.req.query("page") || "1";
  if ((query === "genre" || query === "producer") && !category) {
    throw new validationError(`category is require for query ${query}`);
  }
  if (query !== "genre" && query !== "producer" && query !== "az-list" && category) {
    category = null;
  }
  let nromalizeCategory = category && category.replaceAll(" ", "-").toLowerCase();
  if (nromalizeCategory === "martial-arts") nromalizeCategory = "marial-arts";
  const endpoint = category ? `/${query}/${nromalizeCategory}?page=${page}` : `/${query}?page=${page}`;
  const result = await axiosInstance(endpoint);
  if (!result.success || !result.data) {
    throw new validationError(result.message || "make sure given endpoint is correct");
  }
  const response = extractListPage(result.data);
  if (response.response.length < 1) throw new NotFoundError();
  return response;
};
var listpage_controller_default = listpageController;

// src/controllers/search.controller.ts
var searchController = async (c) => {
  const keyword = c.req.query("keyword") || c.req.query("q") || c.req.query("query") || null;
  const page = c.req.query("page") || "1";
  if (!keyword) throw new validationError("query is required");
  const noSpaceKeyword = keyword.trim().toLowerCase().replace(/\s+/g, "+");
  const endpoint = `/search?keyword=${noSpaceKeyword}&page=${page}`;
  const result = await axiosInstance(endpoint);
  if (!result.success || !result.data) {
    throw new validationError(result.message || "make sure given endpoint is correct");
  }
  const parsed = extractListPage(result.data);
  if (parsed.response.length < 1) {
    throw new NotFoundError("page not found");
  }
  const animes = parsed.response.map((item) => ({
    id: item.id,
    name: item.title,
    jname: item.alternativeTitle,
    poster: item.poster,
    duration: item.duration,
    type: item.type,
    rating: null,
    episodes: item.episodes
  }));
  return {
    animes,
    // Keep legacy field used by this repo's README / older clients
    response: parsed.response,
    pageInfo: parsed.pageInfo,
    currentPage: parsed.pageInfo.currentPage,
    hasNextPage: parsed.pageInfo.hasNextPage,
    totalPages: parsed.pageInfo.totalPages,
    top10: parsed.top10,
    genres: parsed.genres
  };
};
var search_controller_default = searchController;

// src/extractor/extractSuggestions.ts
import { load as load4 } from "cheerio";
var extractSuggestions = (html) => {
  const $ = load4(html);
  const response = [];
  const allEl = $(".nav-item");
  const items = allEl.toArray().splice(0, allEl.length - 2);
  $(items).each((i, el) => {
    const obj = {
      title: null,
      alternativeTitle: null,
      poster: null,
      id: null,
      aired: null,
      type: null,
      duration: null
    };
    obj.id = $(el).attr("href")?.split("/").pop()?.split("?").at(0) || null;
    obj.poster = $(el).find(".film-poster-img").attr("data-src") || null;
    const titleEL = $(el).find(".film-name");
    obj.title = titleEL.text() || null;
    obj.alternativeTitle = titleEL.attr("data-jname") || null;
    const infoEl = $(el).find(".film-infor");
    obj.aired = infoEl.find("span").first().text() || null;
    obj.type = infoEl.contents().filter((i2, el2) => {
      return el2.type === "text" && $(el2).text().trim() !== "";
    }).text().trim();
    obj.duration = infoEl.find("span").last().text() || null;
    response.push(obj);
  });
  return response;
};

// src/controllers/suggestion.controller.ts
var suggestionController = async (c) => {
  const keyword = c.req.query("keyword") || c.req.query("q") || c.req.query("query") || null;
  if (!keyword) throw new validationError("query is required");
  const noSpaceKeyword = keyword.trim().toLowerCase().replace(/\s+/g, "+");
  const endpoint = `/ajax/search/suggest?keyword=${noSpaceKeyword}`;
  const result = await axiosInstance(endpoint, {
    headers: { Referer: `${config_default.baseurl}/home` }
  });
  if (!result.success || !result.data) {
    throw new validationError(result.message || "suggestion not found");
  }
  const jsonData = JSON.parse(result.data);
  const response = extractSuggestions(jsonData.html);
  return response;
};
var suggestion_controller_default = suggestionController;

// src/extractor/extractCharacters.ts
import { load as load5 } from "cheerio";
var extractCharacters = (html) => {
  const $ = load5(html);
  const response = [];
  const paginationEl = $(".pre-pagination .pagination .page-item");
  let currentPage, hasNextPage, totalPages;
  if (!paginationEl.length) {
    currentPage = 1;
    hasNextPage = false;
    totalPages = 1;
  } else {
    currentPage = Number(paginationEl.find(".active .page-link").text());
    hasNextPage = !paginationEl.last().hasClass("active");
    totalPages = hasNextPage ? Number(paginationEl.last().find(".page-link").attr("data-url")?.split("page=").at(-1)) : Number(paginationEl.last().find(".page-link").text());
  }
  const pageInfo = {
    totalPages,
    currentPage,
    hasNextPage
  };
  const characters = $(".bac-item");
  if (!characters.length) return { response };
  $(characters).each((i, el) => {
    const obj = {
      name: null,
      id: null,
      imageUrl: null,
      role: null,
      voiceActors: []
    };
    const characterDetail = $(el).find(".per-info").first();
    const voiceActorsDetail = $(el).find(".per-info-xx").length ? $(el).find(".per-info-xx") : $(el).find(".rtl");
    obj.name = $(characterDetail).find(".pi-detail .pi-name a").text();
    obj.role = $(characterDetail).find(".pi-detail .pi-cast").text();
    obj.id = $(characterDetail).find(".pi-avatar").length ? $(characterDetail).find(".pi-avatar").attr("href")?.replace(/^\//, "").replace("/", ":") || null : null;
    obj.imageUrl = $(characterDetail).find(".pi-avatar img").attr("data-src") || null;
    if (!voiceActorsDetail.length) {
      response.push(obj);
      return;
    }
    const hasMultiple = $(voiceActorsDetail).hasClass("per-info-xx");
    if (hasMultiple) {
      $(voiceActorsDetail).find(".pix-list a").each((index, item) => {
        const innerObj = {
          name: null,
          id: null,
          imageUrl: null,
          cast: null
        };
        innerObj.name = $(item).attr("title") || null;
        innerObj.id = $(item).attr("href")?.replace(/^\//, "").replace("/", ":") || null;
        innerObj.imageUrl = $(item).find("img").attr("data-src") || null;
        obj.voiceActors.push(innerObj);
      });
    } else {
      const innerObj = {
        name: null,
        id: null,
        imageUrl: null,
        cast: null
      };
      innerObj.id = $(voiceActorsDetail).find(".pi-avatar").length ? $(voiceActorsDetail).find(".pi-avatar").attr("href")?.replace(/^\//, "").replace("/", ":") || null : null;
      innerObj.imageUrl = $(voiceActorsDetail).find(".pi-avatar img").attr("data-src") || null;
      innerObj.name = $(voiceActorsDetail).find(".pi-avatar img").attr("alt") || null;
      innerObj.cast = $(voiceActorsDetail).find(".pi-cast").text();
      obj.voiceActors.push(innerObj);
    }
    response.push(obj);
  });
  return { pageInfo, response };
};

// src/controllers/characters.controller.ts
var charactersController = async (c) => {
  try {
    const id = c.req.param("id");
    const page = c.req.query("page") || "1";
    if (!id) throw new validationError("id is required");
    const idNum = id.split("-").pop();
    const endpoint = `/ajax/character/list/${idNum}?page=${page}`;
    const result = await axiosInstance(endpoint, {
      headers: { Referer: `${config_default.baseurl}/home` }
    });
    if (!result.success || !result.data) {
      throw new validationError(result.message || "characters not found");
    }
    const response = extractCharacters(result.data);
    return response;
  } catch (err) {
    if (err instanceof Error) {
      console.log(err.message);
    } else {
      console.log(err);
    }
    throw new validationError("characters not found");
  }
};
var characters_controller_default = charactersController;

// src/extractor/extractCharacterDetail.ts
import { load as load6 } from "cheerio";
var extractCharacterDetail = (html) => {
  const $ = load6(html);
  const transformId = (id) => {
    if (!id) return null;
    return id.replace(/^\//, "").replace("/", ":");
  };
  const whoIsHe = $("nav .breadcrumb .active").prev().find("a").text() === "People" ? "people" : "character";
  const obj = {
    name: null,
    type: whoIsHe,
    japanese: null,
    imageUrl: null,
    bio: null
  };
  obj.imageUrl = $(".actor-page-wrap .avatar img").attr("src") || null;
  const allDetails = $(".apw-detail");
  obj.name = allDetails.find(".name").text();
  obj.japanese = allDetails.find(".sub-name").text();
  obj.bio = allDetails.find(".tab-content #bio .bio").html()?.trim() || null;
  if (whoIsHe === "character") {
    obj.animeAppearances = [];
    allDetails.find(".tab-content #animeography .anif-block-ul .ulclear li").each((i, el) => {
      const innerObj = {
        title: null,
        alternativeTitle: null,
        id: null,
        poster: null,
        role: null,
        type: null
      };
      const titleEl = $(el).find(".dynamic-name");
      innerObj.title = titleEl.attr("title") || null;
      innerObj.alternativeTitle = titleEl.attr("data-jname") || null;
      innerObj.id = transformId(titleEl.attr("href"));
      innerObj.poster = $(el).find(".film-poster .film-poster-img").attr("src") || null;
      innerObj.role = $(el).find(".fd-infor .fdi-item").first().text().split(" ").shift() || null;
      innerObj.type = $(el).find(".fd-infor .fdi-item").last().text();
      obj.animeAppearances?.push(innerObj);
    });
    obj.voiceActors = [];
    allDetails.find("#voiactor .sub-box-list .per-info").each((i, el) => {
      const innerObj = {
        name: null,
        imageUrl: null,
        id: null,
        language: null
      };
      innerObj.imageUrl = $(el).find(".pi-avatar img").attr("src") || null;
      innerObj.name = $(el).find(".pi-name a").text();
      innerObj.id = transformId($(el).find(".pi-name a").attr("href"));
      innerObj.language = $(el).find(".pi-cast").text();
      obj.voiceActors?.push(innerObj);
    });
  } else {
    obj.voiceActingRoles = [];
    $("#voice .bac-list-wrap .bac-item").each((i, el) => {
      const animeInfo = $(el).find(".per-info.anime-info");
      const characterInfo = $(el).find(".per-info.rtl");
      const innerObj = {
        anime: {
          title: null,
          poster: null,
          id: null,
          typeAndYear: null
        },
        character: {
          name: null,
          imageUrl: null,
          id: null,
          role: null
        }
      };
      innerObj.anime.title = animeInfo.find(".pi-name a").text().trim();
      innerObj.anime.id = animeInfo.find(".pi-name a").attr("href")?.split("/").pop() || null;
      innerObj.anime.poster = animeInfo.find(".pi-avatar img").attr("src") || null;
      innerObj.anime.typeAndYear = animeInfo.find(".pi-cast").text().trim();
      innerObj.character.name = characterInfo.find(".pi-name a").text().trim();
      innerObj.character.id = transformId(characterInfo.find(".pi-name a").attr("href"));
      innerObj.character.imageUrl = characterInfo.find(".pi-avatar img").attr("src") || null;
      innerObj.character.role = characterInfo.find(".pi-cast").text().trim();
      obj.voiceActingRoles?.push(innerObj);
    });
  }
  return obj;
};

// src/controllers/characterDetail.controller.ts
var characterDetailConroller = async (c) => {
  const id = c.req.param("id");
  if (!id) throw new validationError("id is required");
  const result = await axiosInstance(`/${id.replace(":", "/")}`);
  if (!result.success || !result.data) {
    throw new validationError(result.message || "make sure given endpoint is correct");
  }
  const response = extractCharacterDetail(result.data);
  return response;
};
var characterDetail_controller_default = characterDetailConroller;

// src/extractor/extractEpisodes.ts
import { load as load7 } from "cheerio";
function watchPathFromHref(href) {
  if (!href) return null;
  try {
    if (/^https?:\/\//i.test(href)) {
      const u = new URL(href);
      return `${u.pathname.replace(/^\/watch\/?/, "")}${u.search}`.replace(/^\//, "");
    }
  } catch {
  }
  return href.replace(/^\/?watch\/?/, "").replace(/^\//, "");
}
var extractEpisodes = (html) => {
  const $ = load7(html);
  const response = [];
  $(".ssl-item.ep-item, .ep-item").each((_, el) => {
    const $el = $(el);
    const hrefPath = watchPathFromHref($el.attr("href"));
    const numberAttr = $el.attr("data-number");
    const episodeNumber = numberAttr ? Number(numberAttr) : response.length + 1;
    response.push({
      title: $el.attr("title") || $el.find(".ep-name").text().trim() || null,
      alternativeTitle: $el.find(".ep-name.e-dynamic-name").attr("data-jname") || null,
      // aniwatch-style: one-piece-1?ep=1 (use ? in API, :: legacy optional)
      id: hrefPath ? hrefPath.replace("?", "::") : null,
      isFiller: $el.hasClass("ssl-item-filler") || $el.hasClass("filler"),
      episodeNumber: Number.isFinite(episodeNumber) ? episodeNumber : response.length + 1
    });
  });
  return response;
};

// src/utils/themeAjax.ts
function htmlFromAjax(payload) {
  try {
    const parsed = JSON.parse(payload);
    if (typeof parsed?.html === "string") return parsed.html;
  } catch {
  }
  return payload;
}
function animeNumericId(animeId) {
  const num = animeId.split("-").at(-1);
  if (!num || !/^\d+$/.test(num)) {
    throw new Error(`Invalid anime id: ${animeId}`);
  }
  return num;
}
function episodeNumericId(episodeId) {
  const normalized = episodeId.replace("::", "?");
  const fromQuery = normalized.match(/[?&]ep=(\d+)/i)?.[1];
  if (fromQuery) return fromQuery;
  if (/^\d+$/.test(normalized)) return normalized;
  throw new Error(`Invalid episode id: ${episodeId}`);
}
function animeSlugFromEpisodeId(episodeId) {
  const normalized = episodeId.replace("::", "?");
  const slug = normalized.split("?")[0]?.trim();
  return slug || null;
}
async function fetchTheme(path, refererPath) {
  const referer = refererPath ? `${config_default.baseurl}${refererPath.startsWith("/") ? refererPath : `/${refererPath}`}` : `${config_default.baseurl}/`;
  return axiosInstance(`/api/theme/${path.replace(/^\//, "")}`, {
    headers: {
      Referer: referer,
      "X-Requested-With": "XMLHttpRequest",
      Accept: "application/json, text/javascript, */*; q=0.01"
    }
  });
}

// src/controllers/episodes.controller.ts
var episodesController = async (c) => {
  const id = c.req.param("id");
  if (!id) throw new validationError("id is required");
  const idNum = animeNumericId(id);
  const result = await fetchTheme(`episode/list/${idNum}`, `/watch/${id}`);
  if (!result.success || !result.data) {
    throw new validationError(result.message || "make sure the id is correct", {
      validIdEX: "one-piece-1"
    });
  }
  const extracted = extractEpisodes(htmlFromAjax(result.data));
  const episodes = extracted.map((ep) => ({
    title: ep.title,
    alternativeTitle: ep.alternativeTitle,
    episodeId: ep.id?.includes("::") ? ep.id.replace("::", "?") : ep.id,
    number: ep.episodeNumber,
    isFiller: ep.isFiller,
    // legacy fields
    id: ep.id,
    episodeNumber: ep.episodeNumber
  }));
  return {
    totalEpisodes: episodes.length,
    episodes
  };
};
var episodes_controller_default = episodesController;

// src/services/megaplay.ts
import { createDecipheriv } from "node:crypto";
import { load as load8 } from "cheerio";
var MEGAPLAY_KEY = Buffer.alloc(32);
Buffer.from("i?LMTAx0Q6,:}50U", "utf8").copy(MEGAPLAY_KEY);
var MEGAPLAY_IV = Buffer.alloc(16);
Buffer.from("W0;27ToaUpl_P%'c", "utf8").copy(MEGAPLAY_IV);
var DEFAULT_UA = config_default.headers?.["User-Agent"] || "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0";
function b64urlToBuf(s) {
  const pad = s.length % 4 === 0 ? "" : "=".repeat(4 - s.length % 4);
  return Buffer.from(s.replace(/-/g, "+").replace(/_/g, "/") + pad, "base64");
}
function decryptMegaPlayEnc(enc) {
  const decipher = createDecipheriv("aes-256-cbc", MEGAPLAY_KEY, MEGAPLAY_IV);
  return Buffer.concat([decipher.update(b64urlToBuf(enc)), decipher.final()]).toString("utf8");
}
function parseThemeServers(html) {
  const $ = load8(html);
  const servers = [];
  let idx = 0;
  $(".server-item[data-hash]").each((_, el) => {
    const $el = $(el);
    const hash = $el.attr("data-hash");
    if (!hash) return;
    let embedUrl = "";
    try {
      embedUrl = Buffer.from(hash, "base64").toString("utf8");
    } catch {
      return;
    }
    idx += 1;
    servers.push({
      type: ($el.attr("data-type") || "sub").toLowerCase(),
      serverName: ($el.attr("data-server-name") || $el.text().trim() || `server-${idx}`).trim(),
      serverId: idx,
      embedUrl
    });
  });
  return servers;
}
function pickServer(servers, serverName, category) {
  const cat = category.toLowerCase();
  const want = serverName.toLowerCase().replace(/\s+/g, "-");
  const pool = servers.filter((s) => s.type === cat);
  const exact = pool.find((s) => s.serverName.toLowerCase().replace(/\s+/g, "-") === want) || pool.find((s) => s.serverName.toLowerCase().includes(want.replace(/-/g, " "))) || pool.find((s) => s.serverName.toLowerCase().includes(want));
  if (exact) return exact;
  return pool.find((s) => /megaplay/i.test(s.embedUrl) && /hd-?1/i.test(s.serverName)) || pool.find((s) => /megaplay/i.test(s.embedUrl)) || pool[0] || null;
}
async function fetchText(url, headers) {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 15e3);
  try {
    const res = await fetch(url, { headers, signal: controller.signal });
    if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
    return await res.text();
  } finally {
    clearTimeout(timeoutId);
  }
}
function extractMegaPlayIds(embedHtml) {
  const $ = load8(embedHtml);
  const player = $("#megaplay-player, [data-id][data-realid]").first();
  const id = player.attr("data-id");
  if (id) {
    return { id, realId: player.attr("data-realid") || void 0 };
  }
  const m = embedHtml.match(/data-id=["'](\d+)["']/);
  return m ? { id: m[1] } : null;
}
function resolveM3u8FromDecrypted(decrypted) {
  const trimmed = decrypted.trim();
  if (/^https?:\/\//i.test(trimmed) && /\.m3u8/i.test(trimmed)) return trimmed;
  try {
    const parsed = JSON.parse(trimmed);
    if (typeof parsed?.file === "string") return parsed.file;
    if (typeof parsed?.url === "string") return parsed.url;
    if (Array.isArray(parsed) && typeof parsed[0]?.file === "string") return parsed[0].file;
  } catch {
  }
  const urlMatch = trimmed.match(/https?:\/\/[^\s"'\\]+\.m3u8[^\s"'\\]*/i);
  return urlMatch?.[0] || null;
}
async function resolveMegaPlaySources(embedUrl) {
  const embedHtml = await fetchText(embedUrl, {
    "User-Agent": DEFAULT_UA,
    Referer: `${config_default.baseurl}/`,
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
  });
  const ids = extractMegaPlayIds(embedHtml);
  if (!ids?.id) {
    throw new Error("Could not find MegaPlay source id in embed");
  }
  const embed = new URL(embedUrl);
  const sParam = embed.searchParams.get("s");
  const getSourcesUrl = new URL(`${embed.origin}/stream/getSources`);
  getSourcesUrl.searchParams.set("id", ids.id);
  if (sParam) getSourcesUrl.searchParams.set("s", sParam);
  const raw = await fetchText(getSourcesUrl.toString(), {
    "User-Agent": DEFAULT_UA,
    Referer: embedUrl,
    "X-Requested-With": "XMLHttpRequest",
    Accept: "*/*"
  });
  let payload;
  try {
    payload = JSON.parse(raw);
  } catch {
    throw new Error("MegaPlay getSources returned non-JSON");
  }
  const enc = typeof payload.enc === "string" && payload.enc || typeof payload.sources === "string" && payload.sources || typeof payload.sources === "object" && payload.sources?.file || "";
  if (!enc) throw new Error("MegaPlay getSources missing encrypted stream");
  const decrypted = decryptMegaPlayEnc(enc);
  const m3u8 = resolveM3u8FromDecrypted(decrypted);
  if (!m3u8) throw new Error("Failed to decrypt MegaPlay stream URL");
  const subtitles = (payload.tracks || []).filter((t) => t.file && (t.kind === "captions" || t.kind === "subtitles" || !t.kind)).map((t) => ({
    lang: t.label || "Unknown",
    url: t.file,
    default: Boolean(t.default)
  }));
  const intro = payload.intro?.start != null && payload.intro?.end != null ? { start: payload.intro.start, end: payload.intro.end } : null;
  const outro = payload.outro?.start != null && payload.outro?.end != null ? { start: payload.outro.start, end: payload.outro.end } : null;
  return {
    headers: {
      Referer: embed.origin + "/",
      "User-Agent": DEFAULT_UA
    },
    sources: [
      {
        url: m3u8,
        isM3U8: true,
        quality: "auto"
      }
    ],
    subtitles,
    intro,
    outro,
    anilistID: null,
    malID: null
  };
}

// src/controllers/servers.controller.ts
function mapServers(servers, type) {
  return servers.filter((s) => s.type === type).map((s) => ({
    serverId: s.serverId,
    serverName: s.serverName.toLowerCase().replace(/\s+/g, "-")
  }));
}
var serversController = async (c) => {
  const animeEpisodeId = c.req.query("animeEpisodeId") || c.req.query("episodeId") || c.req.param("episodeId");
  if (!animeEpisodeId) {
    throw new validationError("animeEpisodeId is required", {
      example: "one-piece-1?ep=1"
    });
  }
  const epNum = episodeNumericId(animeEpisodeId);
  const slug = animeSlugFromEpisodeId(animeEpisodeId);
  const referer = slug ? `/watch/${slug}?ep=${epNum}` : `/`;
  const result = await fetchTheme(`episode/servers?episodeId=${epNum}`, referer);
  if (!result.success || !result.data) {
    throw new validationError(result.message || "could not load episode servers", {
      animeEpisodeId
    });
  }
  const servers = parseThemeServers(htmlFromAjax(result.data));
  const episodeNo = Number(epNum);
  return {
    episodeId: animeEpisodeId.replace("::", "?"),
    episodeNo: Number.isFinite(episodeNo) ? episodeNo : null,
    sub: mapServers(servers, "sub"),
    dub: mapServers(servers, "dub"),
    raw: mapServers(servers, "raw")
  };
};
var servers_controller_default = serversController;

// src/controllers/sources.controller.ts
var sourcesController = async (c) => {
  const animeEpisodeId = c.req.query("animeEpisodeId") || c.req.query("episodeId") || c.req.param("episodeId");
  const server = (c.req.query("server") || "hd-1").toLowerCase();
  const category = (c.req.query("category") || c.req.query("type") || "sub").toLowerCase();
  if (!animeEpisodeId) {
    throw new validationError("animeEpisodeId is required", {
      example: "one-piece-1?ep=1"
    });
  }
  const epNum = episodeNumericId(animeEpisodeId);
  const slug = animeSlugFromEpisodeId(animeEpisodeId);
  const referer = slug ? `/watch/${slug}?ep=${epNum}` : `/`;
  const result = await fetchTheme(`episode/servers?episodeId=${epNum}`, referer);
  if (!result.success || !result.data) {
    throw new validationError(result.message || "could not load episode servers", {
      animeEpisodeId
    });
  }
  const servers = parseThemeServers(htmlFromAjax(result.data));
  const picked = pickServer(servers, server, category);
  if (!picked) {
    throw new validationError(`No ${category} server matching "${server}"`, {
      available: servers.map((s) => ({ type: s.type, serverName: s.serverName }))
    });
  }
  if (!/megaplay/i.test(picked.embedUrl)) {
    const megaplayFallback = pickServer(
      servers.filter((s) => /megaplay/i.test(s.embedUrl)),
      "hd-1",
      category
    );
    if (!megaplayFallback) {
      throw new validationError(
        `Server "${picked.serverName}" is not a MegaPlay embed; no stream extractor available`,
        { embedUrl: picked.embedUrl }
      );
    }
    const stream2 = await resolveMegaPlaySources(megaplayFallback.embedUrl);
    return {
      ...stream2,
      server: megaplayFallback.serverName.toLowerCase().replace(/\s+/g, "-"),
      category
    };
  }
  const stream = await resolveMegaPlaySources(picked.embedUrl);
  return {
    ...stream,
    server: picked.serverName.toLowerCase().replace(/\s+/g, "-"),
    category
  };
};
var sources_controller_default = sourcesController;

// src/controllers/allGenres.controller.ts
var allGenres = [
  "action",
  "adventure",
  "cars",
  "comedy",
  "dementia",
  "demons",
  "drama",
  "ecchi",
  "fantasy",
  "game",
  "harem",
  "historical",
  "horror",
  "isekai",
  "josei",
  "kids",
  "magic",
  "martial arts",
  "mecha",
  "military",
  "music",
  "mystery",
  "parody",
  "police",
  "psychological",
  "romance",
  "samurai",
  "school",
  "sci-fi",
  "seinen",
  "shoujo",
  "shoujo ai",
  "shounen",
  "shounen ai",
  "slice of life",
  "space",
  "sports",
  "super power",
  "supernatural",
  "thriller",
  "vampire"
];
var allGenresController = () => {
  return allGenres;
};
var allGenres_controller_default = allGenresController;

// src/extractor/extractNextEpisodeSchedule.ts
import { load as load9 } from "cheerio";
var extractNextEpisodeSchedule = (html) => {
  const $ = load9(html);
  const scheduleElement = $("#schedule-date");
  const scheduleDate = scheduleElement.attr("data-value");
  if (scheduleDate) {
    return scheduleDate;
  }
  const rawString = $(".tick-item.tick-eps.schedule").text().trim();
  return rawString || null;
};

// src/controllers/nextEpisodeSchedule.controller.ts
var nextEpisodeSchaduleController = async (c) => {
  const id = c.req.param("id");
  if (!id) throw new validationError("id is required");
  const data = await axiosInstance("/watch/" + id);
  if (!data.success || !data.data)
    throw new validationError(data.message || "make sure id is correct");
  const response = extractNextEpisodeSchedule(data.data);
  return response;
};
var nextEpisodeSchedule_controller_default = nextEpisodeSchaduleController;

// src/utils/filter.ts
var filterOptions = {
  type: ["all", "movie", "tv", "ova", "special", "music"],
  status: ["all", "finished_airing", "currently_airing", "not_yet_aired"],
  rated: ["all", "g", "pg", "pg-13", "r", "r+", "rx"],
  score: [
    "all",
    "appalling",
    "horrible",
    "very_bad",
    "bad",
    "average",
    "fine",
    "good",
    "very_good",
    "great",
    "masterpiece"
  ],
  season: ["all", "spring", "summer", "fall", "winter"],
  language: ["all", "sub", "dub", "sub_dub"],
  sort: [
    "default",
    "recently_added",
    "recently_updated",
    "score",
    "name_az",
    "release_date",
    "most_watched"
  ],
  genres: [
    "action",
    "adventure",
    "cars",
    "comedy",
    "dementia",
    "demons",
    "mystery",
    "drama",
    "ecchi",
    "fantasy",
    "game",
    "",
    "historical",
    "horror",
    "kids",
    "magic",
    "martial_arts",
    "mecha",
    "music",
    "parody",
    "samurai",
    "romance",
    "school",
    "sci-fi",
    "shoujo",
    "shoujo_ai",
    "shounen",
    "shounen_ai",
    "space",
    "sports",
    "super_power",
    "vampire",
    "",
    "",
    "harem",
    "slice_of_life",
    "supernatural",
    "military",
    "police",
    "psychological",
    "thriller",
    "seinen",
    "josei",
    "isekai"
  ]
};
var filter_default = filterOptions;

// src/controllers/filter.controller.ts
var filterController = async (c) => {
  const {
    // will receive string and send as a string
    keyword = null,
    sort = null,
    // will recieve an array as string will "," saparated and send as "," saparated string
    genres = null,
    // will recieve as string and send as index of that string "see filterOptions"
    type = null,
    status = null,
    rated = null,
    score = null,
    season = null,
    language = null,
    page = "1"
  } = c.req.query();
  const pageNum = Number(page);
  const queryArr = [
    { title: "keyword", val: keyword },
    { title: "sort", val: sort },
    { title: "type", val: type },
    { title: "status", val: status },
    { title: "rated", val: rated },
    { title: "score", val: score },
    { title: "season", val: season },
    { title: "language", val: language },
    { title: "genres", val: genres }
  ];
  const params = new URLSearchParams();
  queryArr.forEach((v) => {
    if (v.val) {
      switch (v.title) {
        case "keyword":
          params.set("keyword", formatKeyword(v.val));
          break;
        case "genres":
          params.set("genres", formatGenres(v.val));
          break;
        case "sort": {
          const formattedSort = formatSort(v.val);
          if (formattedSort) params.set("sort", formattedSort);
          break;
        }
        default: {
          const formattedOption = formatOption(v.title, v.val);
          if (formattedOption) params.set(v.title, formattedOption);
        }
      }
    }
  });
  if (pageNum > 1) params.set("page", String(pageNum));
  const endpoint = keyword ? "/search" : "/filter";
  const queryString = params.toString();
  const url = queryString ? `${endpoint}?${queryString}` : endpoint;
  const result = await axiosInstance(url);
  console.log(result.message);
  if (!result.success || !result.data)
    throw new validationError(result.message || "something went wrong will queries");
  const response = extractListPage(result.data);
  return response;
};
var formatKeyword = (v) => v.toLowerCase();
var formatSort = (v) => {
  const index = filter_default.sort.indexOf(v.toLowerCase().replace(" ", "_"));
  if (index === -1) return null;
  return filter_default.sort[index];
};
var formatGenres = (v) => {
  let indexes = v.split(",").map(
    (genre) => filter_default.genres.indexOf(
      genre.toLowerCase().replaceAll(" ", "_")
    )
  ).filter((i) => i !== -1).map((i) => i + 1);
  return indexes.length > 0 ? indexes.join(",") : "";
};
var formatOption = (k, v) => {
  const index = filter_default[k].indexOf(v);
  if (index === -1) return null;
  return index.toString();
};
var filter_controller_default = filterController;

// src/extractor/extractNews.ts
import * as cheerio from "cheerio";
var extractNews = (html) => {
  const $ = cheerio.load(html);
  const news = [];
  $(".zr-news-list .item").each((i, el) => {
    const obj = {
      id: null,
      title: null,
      description: null,
      thumbnail: null,
      uploadedAt: null,
      url: null
    };
    const link = $(el).find(".zrn-title").attr("href");
    obj.id = link?.split("/").pop() || null;
    obj.url = link || null;
    obj.title = $(el).find(".news-title").text().trim() || null;
    obj.description = $(el).find(".description").text().trim() || null;
    obj.thumbnail = $(el).find(".zrn-image").attr("src") || null;
    obj.uploadedAt = $(el).find(".time-posted").text().trim() || null;
    if (obj.title) {
      news.push(obj);
    }
  });
  return {
    news,
    total: news.length
  };
};

// src/controllers/news.controller.ts
var newsController = async (c) => {
  const page = c.req.query("page") || "1";
  console.log(`Fetching news page ${page} from external API...`);
  const endpoint = page === "1" ? "/news" : `/news?page=${page}`;
  const result = await axiosInstance(endpoint);
  if (!result.success || !result.data) {
    console.error("News fetch failed:", result.message);
    throw new validationError(result.message || "Failed to fetch news");
  }
  return extractNews(result.data);
};
var news_controller_default = newsController;

// src/controllers/random.controller.ts
import * as cheerio2 from "cheerio";
var randomController = async (_c) => {
  console.log("Fetching random anime...");
  const result = await axiosInstance("/home");
  if (!result.success || !result.data) {
    console.error("Random anime fetch failed:", result.message);
    throw new validationError(result.message || "Failed to fetch homepage for random selection");
  }
  const $ = cheerio2.load(result.data);
  const animes = [];
  $(".flw-item").each((i, el) => {
    const link = $(el).find(".film-name .dynamic-name").attr("href");
    const id = link?.split("/").pop();
    if (id) animes.push(id);
  });
  if (animes.length === 0) {
    throw new validationError("No anime found");
  }
  const randomId = animes[Math.floor(Math.random() * animes.length)];
  return { id: randomId };
};
var random_controller_default = randomController;

// src/extractor/extractSchedule.ts
import { load as load12 } from "cheerio";
var extractSchedule = (html) => {
  const $ = load12(html);
  const response = [];
  $("a").each((i, element) => {
    const obj = {
      title: null,
      alternativeTitle: null,
      id: null,
      time: null,
      episode: null
    };
    const el = $(element);
    obj.id = el.attr("href")?.replace("/", "") || null;
    obj.time = el.find(".time").text() || null;
    obj.title = el.find(".film-name").text().trim() || null;
    obj.alternativeTitle = el.find(".film-name").attr("data-jname")?.trim() || null;
    obj.episode = Number(el.find(".btn-play").text().trim().split("Episode ").pop()) || null;
    response.push(obj);
  });
  return response;
};

// src/controllers/schedules.controller.ts
async function schedulesController(c) {
  const today = /* @__PURE__ */ new Date();
  const dateParam = c.req.query("date");
  let startDate = today;
  if (dateParam) {
    const [year, month, day] = dateParam.split("-").map(Number);
    startDate = new Date(year, month - 1, day);
    if (isNaN(startDate.getTime())) {
      throw new validationError("Invalid date format. Use YYYY-MM-DD");
    }
  }
  const dates = [];
  for (let i = 0; i < 7; i++) {
    const d = new Date(startDate);
    d.setDate(startDate.getDate() + i);
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    dates.push(`${year}-${month}-${day}`);
  }
  try {
    const promises = dates.map(async (date) => {
      const ajaxUrl = `/ajax/schedule/list?tzOffset=-330&date=${date}`;
      try {
        const result = await axiosInstance(ajaxUrl, {
          headers: { Referer: `${config_default.baseurl}/home` }
        });
        if (!result.success || !result.data) {
          throw new Error(result.message || "Failed to fetch");
        }
        const jsonData = JSON.parse(result.data);
        return {
          date,
          shows: extractSchedule(jsonData.html)
        };
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : "Unknown error";
        console.error(`Failed to fetch schedule for ${date}: ${errorMessage}`);
        return {
          date,
          shows: [],
          error: "Failed to fetch"
        };
      }
    });
    const results = await Promise.all(promises);
    const response = {};
    results.forEach((result) => {
      response[result.date] = result.shows;
    });
    return {
      success: true,
      data: response
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    console.error(errorMessage);
    throw new validationError("Failed to fetch schedules");
  }
}
var schedules_controller_default = schedulesController;

// src/extractor/extractTopSearch.ts
import * as cheerio3 from "cheerio";
var extractTopSearch = (html) => {
  const $ = cheerio3.load(html);
  const topSearch = [];
  $(".xhashtag .item").each((i, el) => {
    const link = $(el).attr("href") || null;
    const id = link ? link.split("/").pop()?.split("?")[0] || null : null;
    topSearch.push({
      title: $(el).text().trim() || null,
      link,
      id
    });
  });
  return topSearch;
};

// src/controllers/topSearch.controller.ts
var topSearchController = async (_c) => {
  console.log("Fetching top search data from external API...");
  const result = await axiosInstance("/");
  if (!result.success || !result.data) {
    console.error("Top search fetch failed:", result.message);
    throw new validationError(result.message || "Failed to fetch top search");
  }
  return extractTopSearch(result.data);
};
var topSearch_controller_default = topSearchController;

// src/routes/routes.ts
var router = new Hono();
router.get("/home", handler_default(homepage_controller_default));
router.get("/hianime/home", handler_default(homepage_controller_default));
router.get("/top-search", handler_default(topSearch_controller_default));
router.get("/schedules", handler_default(schedules_controller_default));
router.get("/schedule/next/:id", handler_default(nextEpisodeSchedule_controller_default));
router.get("/anime/:id", handler_default(detailpage_controller_default));
router.get("/animes/:query/:category?", handler_default(listpage_controller_default));
router.get("/search", handler_default(search_controller_default));
router.get("/hianime/search", handler_default(search_controller_default));
router.get(
  "/filter/options",
  handler_default(async () => filter_default)
);
router.get("/filter", handler_default(filter_controller_default));
router.get("/suggestion", handler_default(suggestion_controller_default));
router.get("/characters/:id", handler_default(characters_controller_default));
router.get("/character/:id", handler_default(characterDetail_controller_default));
router.get("/episodes/:id", handler_default(episodes_controller_default));
router.get("/hianime/anime/:id/episodes", handler_default(episodes_controller_default));
router.get("/anime/:id/episodes", handler_default(episodes_controller_default));
router.get("/hianime/episode/servers", handler_default(servers_controller_default));
router.get("/episode/servers", handler_default(servers_controller_default));
router.get("/hianime/episode/sources", handler_default(sources_controller_default));
router.get("/episode/sources", handler_default(sources_controller_default));
router.get("/genres", handler_default(allGenres_controller_default));
router.get("/news", handler_default(news_controller_default));
router.get("/random", handler_default(random_controller_default));
var routes_default = router;

// src/app.ts
import { logger } from "hono/logger";
var app = new Hono2();
var origins = config_default.origin.includes(",") ? config_default.origin.split(",").map((o) => o.trim()) : config_default.origin === "*" ? "*" : [config_default.origin];
app.use(
  "*",
  cors({
    origin: origins,
    allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allowHeaders: ["Content-Type", "Authorization", "X-Requested-With", "X-Api-Key"],
    exposeHeaders: ["Content-Length", "X-Request-Id"],
    maxAge: 600,
    credentials: true
  })
);
if (!config_default.isProduction || config_default.enableLogging) {
  app.use("/api/v2/*", logger());
}
app.get("/ping", (c) => {
  return c.json({
    status: "ok",
    timestamp: (/* @__PURE__ */ new Date()).toISOString(),
    environment: config_default.isVercel ? "vercel" : "self-hosted"
  });
});
app.get("/favicon.ico", (c) => {
  return c.body(null, 204);
});
app.route("/api/v2", routes_default);
app.onError((err, c) => {
  if (err instanceof AppError) {
    return fail(c, err.message, err.statusCode, err.details);
  }
  console.error("Unexpected Error:", err.message);
  if (!config_default.isProduction) {
    console.error("Stack:", err.stack);
  }
  return fail(c, "Internal server error", 500);
});
app.notFound((c) => {
  return fail(c, "Route not found", 404);
});
var app_default = app;

// src/vercel-entry.ts
var config2 = {
  api: {
    bodyParser: false
  }
};
var vercel_entry_default = handle(app_default);
export {
  config2 as config,
  vercel_entry_default as default
};
